/** Platform-owned final-candidate UI copy. Owner-authored content stays in settings. */
export const PRODUCT_COPY: Record<string, {fr: string; ar: string}> = {
  "The stored receipt is invalid. Reject this request and ask the Agency to upload a valid receipt.": {fr:"Le justificatif enregistré est invalide. Refusez cette demande et demandez à l'agence de transmettre un justificatif valide.",ar:"الإيصال المحفوظ غير صالح. ارفض هذا الطلب واطلب من الوكالة تحميل إيصال صالح."},
  "Suspend this user?": {fr:"Suspendre cet utilisateur ?",ar:"هل تريد تعليق هذا المستخدم؟"},
  "Reactivate this user?": {fr:"Réactiver cet utilisateur ?",ar:"هل تريد إعادة تفعيل هذا المستخدم؟"},
  "Applying…": {fr:"Application…",ar:"جارٍ التطبيق…"},
  "Document review": {fr:"Vérification des documents",ar:"مراجعة الوثائق"},
  "Current workload": {fr:"Charge de travail actuelle",ar:"عبء العمل الحالي"},
  "Next action": {fr:"Prochaine action",ar:"الإجراء التالي"},
  "Registration is blocked in each language until its approved Terms and Privacy versions are published.": {fr:"L’inscription est bloquée dans chaque langue jusqu’à la publication de ses Conditions et de sa Confidentialité approuvées.",ar:"يتوقف التسجيل بكل لغة حتى نشر نسختي الشروط والخصوصية المعتمدتين لتلك اللغة."},
  "No verification documents are linked to this agency.": {fr:"Aucun document de vérification n’est lié à cette agence.",ar:"لا توجد وثائق تحقق مرتبطة بهذه الوكالة."},
  "Saving.": {fr:"Enregistrement.",ar:"جارٍ الحفظ."},
  "Removing.": {fr:"Suppression.",ar:"جارٍ الإزالة."},
  "Uploading.": {fr:"Téléversement.",ar:"جارٍ الرفع."},
  "Reconciliation scan completed.": {fr:"Analyse de régularisation terminée.",ar:"اكتمل فحص التسوية."},
  "Reconciliation note recorded.": {fr:"Note de régularisation enregistrée.",ar:"تم تسجيل ملاحظة التسوية."},
  "Choose a valid reconciliation outcome.": {fr:"Choisissez un résultat de régularisation valide.",ar:"اختر نتيجة تسوية صالحة."},
  "Enter a meaningful reconciliation note.": {fr:"Saisissez une note de régularisation explicite.",ar:"أدخل ملاحظة تسوية واضحة."},
  "The genuine original document or storage object is still missing.": {fr:"Le document original authentique ou son fichier stocké est toujours manquant.",ar:"ما زالت الوثيقة الأصلية الحقيقية أو ملفها المخزن مفقودًا."},
  "Activity": {fr:"Activité", ar:"النشاط"},
  "Created applications": {fr:"Demandes créées", ar:"الطلبات المنشأة"},
  "Submitted applications": {fr:"Demandes soumises", ar:"الطلبات المرسلة"},
  "Decisions recorded": {fr:"Décisions enregistrées", ar:"القرارات المسجلة"},
  "Creation date in the selected period": {fr:"Date de création dans la période sélectionnée", ar:"تاريخ الإنشاء ضمن الفترة المختارة"},
  "Submission date in the selected period": {fr:"Date de soumission dans la période sélectionnée", ar:"تاريخ الإرسال ضمن الفترة المختارة"},
  "Decision date in the selected period": {fr:"Date de décision dans la période sélectionnée", ar:"تاريخ القرار ضمن الفترة المختارة"},
  "Submissions in the selected period": {fr:"Soumissions dans la période sélectionnée", ar:"الإرسالات ضمن الفترة المختارة"},
  "Current assignments; independent of the selected event period": {fr:"Affectations actuelles, indépendantes de la période d’activité sélectionnée", ar:"التعيينات الحالية مستقلة عن فترة الأحداث المختارة"},
  "Document review metrics use the review date.": {fr:"Les indicateurs de vérification des documents utilisent la date de vérification.", ar:"تستخدم مؤشرات مراجعة الوثائق تاريخ المراجعة."},
  "Required for priority changes (at least 10 characters).": {fr:"Obligatoire pour les changements de priorité (10 caractères minimum).", ar:"مطلوب لتغيير الأولوية (10 أحرف على الأقل)."},
  "Dossiers can only be assigned to active ESSAFARIA staff.": {fr:"Les dossiers ne peuvent être affectés qu’à des membres actifs de l’équipe ESSAFARIA.", ar:"يمكن تعيين الملفات لأعضاء فريق ESSAFARIA النشطين فقط."},
  "Country name and ISO code require review": {fr:"Nom de pays et code ISO à vérifier", ar:"يجب مراجعة اسم البلد ورمز ISO"},
  "Possible test catalogue data": {fr:"Données de test possibles dans le catalogue", ar:"قد يحتوي الكتالوج على بيانات اختبار"},
  "Missing programme translations": {fr:"Traductions du programme manquantes", ar:"ترجمات البرنامج مفقودة"},
  "Unavailable destination": {fr:"Destination indisponible", ar:"الوجهة غير متاحة"},
  "Unavailable visa category": {fr:"Catégorie de visa indisponible", ar:"فئة التأشيرة غير متاحة"},
  "Review DZD price": {fr:"Prix DZD à vérifier", ar:"مراجعة السعر بـ DZD"},
  "Review processing times": {fr:"Délais de traitement à vérifier", ar:"مراجعة مدد المعالجة"},
  "View final dossier": {fr:"Consulter le dossier final", ar:"عرض الملف النهائي"},
  "Await requested documents": {fr:"En attente des documents demandés", ar:"في انتظار الوثائق المطلوبة"},
  "Review submitted documents": {fr:"Vérifier les documents transmis", ar:"مراجعة الوثائق المقدمة"},
  "Process application": {fr:"Traiter la demande", ar:"معالجة الطلب"},
  "Brand identity": {fr:"Identité de marque", ar:"هوية العلامة"},
  "Brand name": {fr:"Nom de marque", ar:"اسم العلامة"},
  "Tagline": {fr:"Signature", ar:"شعار نصي"},
  "The approved palette, typography and spacing are locked for consistent, accessible screens.": {fr:"La palette, la typographie et les espacements approuvés sont protégés pour garantir des écrans cohérents et accessibles.", ar:"الألوان والخطوط والمسافات المعتمدة ثابتة لضمان واجهات متسقة وسهلة الاستخدام."},
  "Platform logo": {fr:"Logo de la plateforme", ar:"شعار المنصة"},
  "PNG, JPEG or WebP up to 2 MB. Shown in the website header, portals and sign-in.": {fr:"PNG, JPEG ou WebP, jusqu’à 2 Mo. Affiché dans l’en-tête, les portails et la connexion.", ar:"PNG أو JPEG أو WebP حتى 2 ميغابايت. يظهر في رأس الموقع والبوابات وتسجيل الدخول."},
  "Save branding": {fr:"Enregistrer la marque", ar:"حفظ العلامة"},
  "Remove logo": {fr:"Supprimer le logo", ar:"إزالة الشعار"},
  "Upload logo": {fr:"Importer le logo", ar:"رفع الشعار"},
  "Brand identity saved.": {fr:"Identité de marque enregistrée.", ar:"تم حفظ هوية العلامة."},
  "Enter a brand name or tagline.": {fr:"Saisissez un nom de marque ou une signature.", ar:"أدخل اسم العلامة أو شعارها النصي."},
  "Brand & public settings": {fr:"Marque et paramètres publics", ar:"العلامة والإعدادات العامة"},
  "Manage identity, public contact details and owner-approved legal content.": {fr:"Gérez l’identité, les coordonnées publiques et les textes juridiques approuvés par le propriétaire.", ar:"إدارة الهوية وبيانات الاتصال العامة والنصوص القانونية المعتمدة من المالك."},
  "Launch content readiness": {fr:"Contenus requis pour le lancement", ar:"جاهزية محتوى الإطلاق"},
  "Owner review required": {fr:"Validation du propriétaire requise", ar:"مراجعة المالك مطلوبة"},
  "Technical checks do not approve company facts, the launch catalogue or legal text.": {fr:"Les vérifications techniques ne valident ni les informations de l’entreprise, ni le catalogue de lancement, ni les textes juridiques.", ar:"الفحوص التقنية لا تعتمد معلومات الشركة أو كتالوج الإطلاق أو النصوص القانونية."},
  "Missing public contact details": {fr:"Coordonnées publiques manquantes", ar:"بيانات الاتصال العامة مفقودة"},
  "Missing approved legal versions": {fr:"Versions juridiques approuvées manquantes", ar:"النسخ القانونية المعتمدة مفقودة"},
  "Registration remains closed until Terms and Privacy are published in EN, FR and AR.": {fr:"L’inscription reste fermée tant que les Conditions et la Confidentialité ne sont pas publiées en EN, FR et AR.", ar:"يبقى التسجيل مغلقًا حتى نشر الشروط والخصوصية بالإنجليزية والفرنسية والعربية."},
  "Catalogue review issues": {fr:"Points à vérifier dans le catalogue", ar:"نقاط مراجعة الكتالوج"},
  "Owner launch checklist": {fr:"Liste de validation du lancement", ar:"قائمة اعتماد الإطلاق"},
  "Confirm the registered company identity, real contact details, office address and office hours before launch.": {fr:"Confirmez l’identité enregistrée de l’entreprise, les coordonnées réelles, l’adresse et les horaires avant le lancement.", ar:"اعتمد هوية الشركة المسجلة وبيانات الاتصال الحقيقية والعنوان وساعات العمل قبل الإطلاق."},
  "Confirm the launch destinations, visa classifications, prices, processing times and document requirements.": {fr:"Confirmez les destinations, les catégories de visas, les prix, les délais et les documents requis au lancement.", ar:"اعتمد وجهات الإطلاق وتصنيفات التأشيرات والأسعار ومدد المعالجة والوثائق المطلوبة."},
  "Website content": {fr:"Contenu du site", ar:"محتوى الموقع"},
  "Public contact details and optional owner-written About copy. Empty fields are omitted from the public site.": {fr:"Coordonnées publiques et présentation rédigée par le propriétaire, facultative. Les champs vides sont omis du site.", ar:"بيانات الاتصال العامة ونص تعريفي اختياري يكتبه المالك. لا تظهر الحقول الفارغة في الموقع."},
  "Contact email": {fr:"E-mail de contact", ar:"البريد الإلكتروني للتواصل"},
  "Contact phone": {fr:"Téléphone de contact", ar:"هاتف التواصل"},
  "Office address": {fr:"Adresse des bureaux", ar:"عنوان المكتب"},
  "Office hours": {fr:"Horaires des bureaux", ar:"ساعات العمل"},
  "LinkedIn URL": {fr:"Lien LinkedIn", ar:"رابط LinkedIn"},
  "Instagram URL": {fr:"Lien Instagram", ar:"رابط Instagram"},
  "X / Twitter URL": {fr:"Lien X / Twitter", ar:"رابط X / Twitter"},
  "About text": {fr:"Texte de présentation", ar:"نص التعريف"},
  "Legal content": {fr:"Contenu juridique", ar:"المحتوى القانوني"},
  "Rendered on the public Privacy and Terms pages in the selected language.": {fr:"Affiché sur les pages publiques Confidentialité et Conditions dans la langue choisie.", ar:"يظهر في صفحات الخصوصية والشروط العامة باللغة المختارة."},
  "Privacy notice": {fr:"Notice de confidentialité", ar:"إشعار الخصوصية"},
  "Terms of service": {fr:"Conditions de service", ar:"شروط الخدمة"},
  "Read-only view": {fr:"Consultation seule", ar:"عرض للقراءة فقط"},
  "Your role cannot modify settings.": {fr:"Votre rôle ne permet pas de modifier les paramètres.", ar:"دورك لا يسمح بتعديل الإعدادات."},
  "Enter a valid contact email.": {fr:"Saisissez un e-mail de contact valide.", ar:"أدخل بريدًا إلكترونيًا صالحًا للتواصل."},
  "Use an http or https social link.": {fr:"Utilisez un lien social http ou https.", ar:"استخدم رابطًا اجتماعيًا يبدأ بـ http أو https."},
  "Website content saved.": {fr:"Contenu du site enregistré.", ar:"تم حفظ محتوى الموقع."},
  "Enter your username or staff email and password.": {fr:"Saisissez votre nom d'utilisateur ou e-mail professionnel et votre mot de passe.", ar:"أدخل اسم المستخدم أو بريد العمل وكلمة المرور."},
  "Invalid username, email or password.": {fr:"Nom d’utilisateur, e-mail ou mot de passe incorrect.", ar:"اسم المستخدم أو البريد أو كلمة المرور غير صحيحة."},
  "Sign-in is temporarily unavailable. Please try again later.": {fr:"La connexion est temporairement indisponible. Réessayez plus tard.", ar:"تسجيل الدخول غير متاح مؤقتًا. حاول لاحقًا."},
  "Service temporarily unavailable. Please try again.": {fr:"Le service est temporairement indisponible. Réessayez.", ar:"الخدمة غير متاحة مؤقتًا. حاول مجددًا."},
  "Your session has expired. Sign in again to continue.": {fr:"Votre session a expiré. Reconnectez-vous pour continuer.", ar:"انتهت جلستك. سجّل الدخول مجددًا للمتابعة."},
  "Your password has been updated. Sign in with your new password.": {fr:"Votre mot de passe a été modifié. Connectez-vous avec votre nouveau mot de passe.", ar:"تم تحديث كلمة المرور. سجّل الدخول بكلمة المرور الجديدة."},
  "Your travellers. Our shared ambition.": {fr:"Vos voyageurs. Notre ambition partagée.", ar:"مسافروكم. طموحنا المشترك."},
  "A dedicated space for ESSAFARIA agency partners.": {fr:"Un espace dédié aux agences partenaires ESSAFARIA.", ar:"مساحة مخصصة للوكالات الشريكة لـ ESSAFARIA."},
  "Partner access": {fr:"Accès partenaires", ar:"دخول الشركاء"},
  "The page you are looking for does not exist or you may not have access to it.": {fr:"Cette page n’existe pas ou vous n’y avez pas accès.", ar:"هذه الصفحة غير موجودة أو لا يمكنك الوصول إليها."},
  "Back to homepage": {fr:"Retour à l’accueil", ar:"العودة إلى الرئيسية"},
  "Something went wrong. Please try again.": {fr:"Une erreur est survenue. Réessayez.", ar:"حدث خطأ. حاول مجددًا."},
  "Please check the form values and try again.": {fr:"Vérifiez les champs du formulaire et réessayez.", ar:"راجع حقول النموذج وحاول مجددًا."},
  "Try again": {fr:"Réessayer", ar:"المحاولة مجددًا"},
  "Loading your workspace…": {fr:"Chargement de votre espace…", ar:"جارٍ تحميل مساحة العمل…"},
  "The connection was interrupted. Check your connection and try again. Your selected files are kept on this page.": {fr:"La connexion a été interrompue. Vérifiez votre connexion et réessayez. Les fichiers sélectionnés restent sur cette page.", ar:"انقطع الاتصال. تحقّق من اتصالك وحاول مجددًا. تبقى الملفات المختارة في هذه الصفحة."},
  "Refresh catalogue and choose again": {fr:"Actualiser le catalogue et choisir à nouveau", ar:"تحديث الكتالوج والاختيار مجددًا"},
  "This programme is unavailable. Refresh the catalogue, choose an available programme and review the price and documents again.": {fr:"Ce programme est indisponible. Actualisez le catalogue, choisissez un programme disponible et vérifiez à nouveau le prix et les documents.", ar:"هذا البرنامج غير متاح. حدّث الكتالوج واختر برنامجًا متاحًا وراجع السعر والوثائق مجددًا."},
  "The upload was interrupted. Check your connection and select the file again.": {fr:"L’envoi a été interrompu. Vérifiez votre connexion et sélectionnez à nouveau le fichier.", ar:"انقطع رفع الملف. تحقّق من اتصالك واختر الملف مجددًا."},
  "Choose a PDF, JPEG, PNG or WebP file up to 2 MB.": {fr:"Choisissez un fichier PDF, JPEG, PNG ou WebP jusqu’à 2 Mo.", ar:"اختر ملف PDF أو JPEG أو PNG أو WebP حتى 2 ميغابايت."},
  "This upload link is unavailable. Contact ESSAFARIA for a new link.": {fr:"Ce lien d’envoi est indisponible. Contactez ESSAFARIA pour un nouveau lien.", ar:"رابط الرفع غير متاح. تواصل مع ESSAFARIA للحصول على رابط جديد."},
  "The file could not be accepted. Check its format and size, then try again.": {fr:"Le fichier n’a pas été accepté. Vérifiez son format et sa taille, puis réessayez.", ar:"تعذر قبول الملف. تحقّق من صيغته وحجمه ثم حاول مجددًا."},
  "The access link could not be generated.": {fr:"Le lien d’accès n’a pas pu être créé.", ar:"تعذر إنشاء رابط الوصول."},
  "The password could not be updated. Please try again.": {fr:"Le mot de passe n’a pas pu être modifié. Réessayez.", ar:"تعذر تحديث كلمة المرور. حاول مجددًا."},
  "Password must be at least 10 characters.": {fr:"Le mot de passe doit comporter au moins 10 caractères.", ar:"يجب أن تتكون كلمة المرور من 10 أحرف على الأقل."},
  "Enter your current password.": {fr:"Saisissez votre mot de passe actuel.", ar:"أدخل كلمة المرور الحالية."},
  "Use letters AND digits in the new password.": {fr:"Utilisez des lettres ET des chiffres dans le nouveau mot de passe.", ar:"استخدم حروفًا وأرقامًا في كلمة المرور الجديدة."},
  "Choose a different password.": {fr:"Choisissez un autre mot de passe.", ar:"اختر كلمة مرور مختلفة."},
  "Hidden from agencies": {fr:"Masqué aux agences", ar:"مخفي عن الوكالات"},
  "Publish to agencies": {fr:"Publier pour les agences", ar:"نشر للوكالات"},
  "Hide from agencies": {fr:"Masquer aux agences", ar:"إخفاء عن الوكالات"},
  "Hidden programmes may be new or previously published. Existing dossiers are preserved.": {fr:"Un programme masqué peut être nouveau ou avoir déjà été publié. Les dossiers existants sont conservés.", ar:"قد يكون البرنامج المخفي جديدًا أو منشورًا سابقًا. تُحفظ الملفات الحالية."},
  "Agency activity": {fr:"Activité de l’agence", ar:"نشاط الوكالة"},
  "Verification documents": {fr:"Documents de vérification", ar:"وثائق التحقق"},
  "View registration": {fr:"Consulter l’inscription", ar:"عرض التسجيل"},
  "No agency activity yet.": {fr:"Aucune activité de l’agence pour le moment.", ar:"لا يوجد نشاط للوكالة بعد."},
  "No verification documents available.": {fr:"Aucun document de vérification disponible.", ar:"لا تتوفر وثائق تحقق."},
  "All agencies": {fr:"Toutes les agences", ar:"جميع الوكالات"},
  "All": {fr:"Tous", ar:"الكل"},
  "DZD wallet": {fr:"Portefeuille DZD", ar:"محفظة DZD"},
  "DZD only.": {fr:"DZD uniquement.", ar:"DZD فقط."},
  "Time zone": {fr:"Fuseau horaire", ar:"المنطقة الزمنية"},
  "Role is assigned by ESSAFARIA.": {fr:"Le rôle est attribué par ESSAFARIA.", ar:"تحدد ESSAFARIA الدور."},
  "Top-up request": {fr:"Demande de rechargement", ar:"طلب تعبئة"},
  "View receipt": {fr:"Consulter le justificatif", ar:"عرض الإيصال"},
  "Await ESSAFARIA review": {fr:"En attente de vérification ESSAFARIA", ar:"في انتظار مراجعة ESSAFARIA"},
  "Await decision": {fr:"En attente de décision", ar:"في انتظار القرار"},
  "View decision": {fr:"Consulter la décision", ar:"عرض القرار"},
  "Review dossier": {fr:"Vérifier le dossier", ar:"مراجعة الملف"},
  "Await agency documents": {fr:"En attente des documents de l’agence", ar:"في انتظار وثائق الوكالة"},
  "Verify documents": {fr:"Vérifier les documents", ar:"التحقق من الوثائق"},
  "Record decision": {fr:"Enregistrer la décision", ar:"تسجيل القرار"},
  "Priority change reason": {fr:"Motif du changement de priorité", ar:"سبب تغيير الأولوية"},
  "Submission metrics use the submission date; decision metrics use the decision date; wallet totals use the transaction date. Exports use these same filters.": {fr:"Les indicateurs de soumission utilisent la date de soumission ; ceux des décisions utilisent la date de décision ; les totaux du portefeuille utilisent la date de transaction. Les exports appliquent ces mêmes filtres.", ar:"تستخدم مؤشرات الإرسال تاريخ الإرسال، ومؤشرات القرارات تاريخ القرار، وإجماليات المحفظة تاريخ المعاملة. تطبق ملفات التصدير الفلاتر نفسها."},
};
