import type { UiLocale } from "@/lib/ui-i18n";
const copies = {
  en: { eyebrow: "For travel agencies", hero: "Their next journey. Your visa partner.", intro: "A clear connection between your agency and the journeys ahead.", partner: "Become a partner", signIn: "Agency sign in", illustration: "Travel illustration", agenciesTitle: "Your agency. More possibilities.", agenciesBody: "Work with ESSAFARIA to prepare your travellers’ visa applications and stay connected throughout the journey.", applyTitle: "Start with a conversation", applyBody: "Tell us your agency name and how to reach you. Our team reviews your request and contacts you if further information is needed.", review: "Agency access follows review.", aboutTitle: "Travel is a shared ambition.", aboutBody: "ESSAFARIA connects travel agencies with visa application support. A professional partnership, built around your travellers.", legalMissing: "This information is awaiting publication. Please contact ESSAFARIA for the approved document before accepting it.", updated: "Effective date" },
  fr: { eyebrow: "Pour les agences de voyage", hero: "Leur prochain voyage. Votre partenaire visa.", intro: "Un lien clair entre votre agence et les voyages à venir.", partner: "Devenir partenaire", signIn: "Connexion agence", illustration: "Illustration de voyage", agenciesTitle: "Votre agence. Plus de possibilités.", agenciesBody: "Avec ESSAFARIA, préparez les demandes de visa de vos voyageurs et restez en contact tout au long du parcours.", applyTitle: "Commençons par un échange", applyBody: "Indiquez le nom de votre agence et vos coordonnées. Notre équipe examine votre demande et vous contacte si des informations complémentaires sont nécessaires.", review: "L’accès agence est accordé après examen.", aboutTitle: "Le voyage, une ambition partagée.", aboutBody: "ESSAFARIA accompagne les agences de voyage dans les demandes de visa de leurs voyageurs. Un partenariat professionnel au service de leurs projets.", legalMissing: "Ces informations sont en attente de publication. Contactez ESSAFARIA pour obtenir le document approuvé avant de l’accepter.", updated: "Date d’entrée en vigueur" },
  ar: { eyebrow: "لوكالات السفر", hero: "رحلتهم القادمة. شريككم للتأشيرات.", intro: "صلة واضحة بين وكالتكم والرحلات القادمة.", partner: "كن شريكاً", signIn: "دخول الوكالة", illustration: "صورة توضيحية للسفر", agenciesTitle: "وكالتكم. إمكانيات أوسع.", agenciesBody: "مع ESSAFARIA، حضّروا طلبات تأشيرات مسافريكم وابقوا على تواصل طوال الرحلة.", applyTitle: "لنبدأ بالتواصل", applyBody: "أخبرونا باسم وكالتكم وبيانات التواصل. يراجع فريقنا طلبكم ويتواصل معكم عند الحاجة إلى معلومات إضافية.", review: "يُمنح دخول الوكالة بعد المراجعة.", aboutTitle: "السفر طموح مشترك.", aboutBody: "تدعم ESSAFARIA وكالات السفر في طلبات تأشيرات مسافريها. شراكة مهنية تتمحور حول مشاريعهم.", legalMissing: "هذه المعلومات تنتظر النشر. يرجى التواصل مع ESSAFARIA للحصول على الوثيقة المعتمدة قبل قبولها.", updated: "تاريخ السريان" },
} as const;
const legalChanged = {
  en: "The legal documents have changed. Refresh this page and review them before submitting.",
  fr: "Les documents juridiques ont changé. Actualisez cette page et relisez-les avant l’envoi.",
  ar: "تغيّرت الوثائق القانونية. حدّث هذه الصفحة وراجعها قبل الإرسال.",
};
export function publicBrandCopy(locale: UiLocale) { return { ...copies[locale], legalChanged: legalChanged[locale] }; }
