import type { UiLocale } from "./ui-i18n";
const centerEn={title:"Account security",intro:"Active sessions (latest 100). Revoking all sessions also invalidates outstanding access credentials.",lastLogin:"Last successful login",events:"Recent security events",authorize:"Authorize Staff enrollment",authorizationHelp:"Verify their identity independently. Share the code through the verified channel; it expires in 30 minutes.",issue:"Issue a single-use authorization",error:"Authorization failed.",unknown:"Unknown device",activity:"Last activity",current:"Current session",other:"Other session",revoke:"Revoke this session",revokeAll:"Revoke all sessions",reset:"Security reset for another Staff account",resetHelp:"Verify the person’s identity outside the portal before resetting MFA. This signs them out everywhere.",staff:"Staff account",reason:"Reason",password:"Confirm your password",resetButton:"Reset MFA and invalidate access",loginEvent:"Successful login",passwordEvent:"Password verified",mfaEvent:"Authenticator security",sessionEvent:"Session security"};
const centerFr:typeof centerEn={title:"Sécurité du compte",intro:"Sessions actives (100 dernières). La révocation de toutes les sessions invalide également les identifiants d’accès en attente.",lastLogin:"Dernière connexion réussie",events:"Événements de sécurité récents",authorize:"Autoriser la configuration du personnel",authorizationHelp:"Vérifiez son identité indépendamment. Communiquez le code par le canal vérifié ; il expire dans 30 minutes.",issue:"Émettre une autorisation à usage unique",error:"Échec de l’autorisation.",unknown:"Appareil inconnu",activity:"Dernière activité",current:"Session actuelle",other:"Autre session",revoke:"Révoquer cette session",revokeAll:"Révoquer toutes les sessions",reset:"Réinitialisation de sécurité d’un autre compte",resetHelp:"Vérifiez l’identité de la personne hors du portail avant de réinitialiser la MFA. Toutes ses sessions seront fermées.",staff:"Compte du personnel",reason:"Motif",password:"Confirmez votre mot de passe",resetButton:"Réinitialiser la MFA et invalider l’accès",loginEvent:"Connexion réussie",passwordEvent:"Mot de passe vérifié",mfaEvent:"Sécurité de l’authentificateur",sessionEvent:"Sécurité des sessions"};
const centerAr:typeof centerEn={title:"أمان الحساب",intro:"الجلسات النشطة (آخر 100). يؤدي إلغاء جميع الجلسات أيضًا إلى إبطال بيانات الدخول المعلقة.",lastLogin:"آخر دخول ناجح",events:"أحداث الأمان الأخيرة",authorize:"تفويض إعداد مصادقة الموظفين",authorizationHelp:"تحقق من هويته بشكل مستقل. أرسل الرمز عبر القناة الموثوقة؛ تنتهي صلاحيته خلال 30 دقيقة.",issue:"إصدار تفويض للاستخدام مرة واحدة",error:"فشل التفويض.",unknown:"جهاز غير معروف",activity:"آخر نشاط",current:"الجلسة الحالية",other:"جلسة أخرى",revoke:"إلغاء هذه الجلسة",revokeAll:"إلغاء جميع الجلسات",reset:"إعادة ضبط أمان حساب موظف آخر",resetHelp:"تحقق من هوية الشخص خارج البوابة قبل إعادة ضبط المصادقة. سيتم تسجيل خروجه من جميع الجلسات.",staff:"حساب الموظف",reason:"السبب",password:"أكّد كلمة المرور",resetButton:"إعادة ضبط المصادقة وإبطال الدخول",loginEvent:"دخول ناجح",passwordEvent:"تم التحقق من كلمة المرور",mfaEvent:"أمان تطبيق المصادقة",sessionEvent:"أمان الجلسات"};
export const securityCenterCopy=(locale:UiLocale)=>({en:centerEn,fr:centerFr,ar:centerAr}[locale]);
const en={title:"Verify staff access",intro:"Staff access requires an authenticator code. Keep recovery codes in a secure password manager.",password:"Confirm your password",setup:"Set up authenticator",key:"Enter this setup key in your authenticator app:",open:"Open authenticator",expires:"This setup expires in 10 minutes.",code:"Authenticator code",recoveryCode:"Authenticator or recovery code",verify:"Verify",save:"Save these single-use recovery codes now. They will not be shown again.",continue:"I saved my recovery codes — continue",error:"Verification failed. Please try again."};
const fr:typeof en={title:"Vérifier l’accès du personnel",intro:"Un code d’authentification est requis. Conservez les codes de récupération dans un gestionnaire de mots de passe sécurisé.",password:"Confirmez votre mot de passe",setup:"Configurer l’authentificateur",key:"Saisissez cette clé dans votre application d’authentification :",open:"Ouvrir l’authentificateur",expires:"Cette configuration expire dans 10 minutes.",code:"Code d’authentification",recoveryCode:"Code d’authentification ou de récupération",verify:"Vérifier",save:"Enregistrez ces codes de récupération à usage unique. Ils ne seront plus affichés.",continue:"Codes enregistrés — continuer",error:"La vérification a échoué. Réessayez."};
const ar:typeof en={title:"التحقق من دخول الموظفين",intro:"يتطلب الدخول رمز تطبيق المصادقة. احتفظ برموز الاسترداد في مدير كلمات مرور آمن.",password:"أكّد كلمة المرور",setup:"إعداد تطبيق المصادقة",key:"أدخل مفتاح الإعداد في تطبيق المصادقة:",open:"فتح تطبيق المصادقة",expires:"تنتهي صلاحية هذا الإعداد خلال 10 دقائق.",code:"رمز المصادقة",recoveryCode:"رمز المصادقة أو الاسترداد",verify:"تحقق",save:"احفظ رموز الاسترداد أحادية الاستخدام الآن. لن تظهر مرة أخرى.",continue:"تم حفظ الرموز — متابعة",error:"فشل التحقق. حاول مرة أخرى."};
export const mfaCopy=(locale:UiLocale)=>({...{en,fr,ar}[locale],...{
  en:{authorization:"Enrollment authorization code",approval:"Ask your security administrator to verify your identity and authorize enrollment."},
  fr:{authorization:"Code d’autorisation de configuration",approval:"Demandez à votre responsable de sécurité de vérifier votre identité et d’autoriser la configuration."},
  ar:{authorization:"رمز تفويض الإعداد",approval:"اطلب من مسؤول الأمن التحقق من هويتك وتفويض إعداد المصادقة."},
}[locale]});
