import { describe, expect, it } from "vitest";
import { suiteSetup } from "./helpers/global-state";
import { testConnectionString } from "./helpers/pg";

suiteSetup();

import { Pool } from "pg";
import { db } from "@/lib/db";
import { walletTransactions } from "@/db/schema";
import { adjustWallet } from "@/lib/wallet";
import { agencyByEmail, userByEmail } from "./helpers/fixtures";
import { databaseSchema } from "@/lib/database-schema";

/**
 * Reference integrity (migration 0015).
 *
 * Regression guard for a defect found by running the real database: the wallet
 * and top-up references were generated by a plpgsql function doing
 * `nextval('wallet_reference_seq'::regclass)`. plpgsql resolves that name at
 * first execution using the session search_path, so in a database hosting both
 * `visa_os_preview` and `visa_os` the SAME table could draw numbers from two
 * different counters — producing duplicate `WLT-…` references and failing a real
 * wallet insert with a unique-constraint error.
 *
 * The contract now: a BEFORE INSERT trigger derives the number from the schema
 * the row is actually inserted into, independent of search_path, and the schema
 * counter is never behind the data it already holds.
 */
describe("human references are schema-safe and collision-free", () => {
  it("wallet references come from the inserting schema, not from search_path", async () => {
    const schema = databaseSchema();
    const pool = new Pool({ connectionString: testConnectionString() });
    try {
      // A second schema with its own counter, deliberately far ahead, proves the
      // trigger follows the *table* (tg_table_schema) and not the session.
      await pool.query(`drop schema if exists ref_probe cascade`);
      await pool.query(`create schema ref_probe`);
      await pool.query(`create sequence ref_probe.wallet_reference_seq`);
      await pool.query(`select setval('ref_probe.wallet_reference_seq', 900001, true)`);
      await pool.query(`
        create table ref_probe.wallet_probe (reference text not null);
        create trigger wallet_probe_reference before insert on ref_probe.wallet_probe
          for each row execute function ${schema}.assign_wallet_reference();
      `);

      const insertWith = async (searchPath: string) => {
        const client = await pool.connect();
        try {
          await client.query(`set search_path to ${searchPath}`);
          const res = await client.query(`insert into ref_probe.wallet_probe (reference) values (null) returning reference`);
          return res.rows[0].reference as string;
        } finally {
          client.release();
        }
      };

      const fromAppPath = await insertWith(`"public"`);
      const fromOtherPath = await insertWith(`"ref_probe", "public"`);
      const y = new Date().getFullYear();

      expect(fromAppPath).toBe(`WLT-${y}-900002`);
      expect(fromOtherPath).toBe(`WLT-${y}-900003`);
      // Both rows came out of the probe schema's own counter: nothing was taken
      // from the application schema's sequence.
      const appCounter = await pool.query(`select last_value from ${schema}.wallet_reference_seq`);
      expect(Number(appCounter.rows[0].last_value)).toBeLessThan(900000);
    } finally {
      await pool.query(`drop schema if exists ref_probe cascade`);
      await pool.end();
    }
  });

  it("top-up references are generated by the same schema-safe mechanism", async () => {
    const schema = databaseSchema();
    const pool = new Pool({ connectionString: testConnectionString() });
    try {
      await pool.query(`drop schema if exists ref_probe_topup cascade`);
      await pool.query(`create schema ref_probe_topup`);
      await pool.query(`create sequence ref_probe_topup.wallet_topup_reference_seq`);
      await pool.query(`create table ref_probe_topup.probe (reference text not null)`);
      await pool.query(`
        create trigger probe_reference before insert on ref_probe_topup.probe
          for each row execute function ${schema}.assign_topup_reference();
      `);
      const client = await pool.connect();
      try {
        await client.query(`set search_path to "public"`);
        const res = await client.query(`insert into ref_probe_topup.probe (reference) values (null) returning reference`);
        expect(res.rows[0].reference).toBe(`TOP-${new Date().getFullYear()}-000001`);
      } finally {
        client.release();
      }
    } finally {
      await pool.query(`drop schema if exists ref_probe_topup cascade`);
      await pool.end();
    }
  });

  it("the application flow still gets unique, server-generated references", async () => {
    const agency = await agencyByEmail("ops@agencya.example");
    const staff = await userByEmail("accounting@test.example");

    // adjustWallet returns the ledger row id; the reference is read back from the DB.
    const firstId = await adjustWallet({ agencyId: agency.id, amount: 500, reason: "reference test 1", actor: staff });
    const secondId = await adjustWallet({ agencyId: agency.id, amount: 250, reason: "reference test 2", actor: staff });

    const rows = await db.select().from(walletTransactions);
    const byId = new Map(rows.map((r) => [r.id, r.reference]));
    const refs = [byId.get(firstId), byId.get(secondId)].filter(Boolean) as string[];
    expect(refs.length).toBe(2);
    for (const ref of refs) expect(ref).toMatch(/^WLT-\d{4}-\d{6}$/);
    expect(new Set(refs).size).toBe(2);

    const all = rows.map((r) => r.reference);
    expect(new Set(all).size).toBe(all.length);
  });

  it("the counter can never fall behind the references already stored", async () => {
    const schema = databaseSchema();
    const pool = new Pool({ connectionString: testConnectionString() });
    try {
      const res = await pool.query(`
        select max(nullif(regexp_replace(reference, '^WLT-[0-9]{4}-', ''), '')::bigint) as max_ref
          from ${schema}.wallet_transactions
         where reference ~ '^WLT-[0-9]{4}-[0-9]+$'
      `);
      const maxRef = Number(res.rows[0].max_ref ?? 0);
      const seq = await pool.query(`select last_value from ${schema}.wallet_reference_seq`);
      expect(Number(seq.rows[0].last_value)).toBeGreaterThanOrEqual(maxRef);
    } finally {
      await pool.end();
    }
  });

  it("references cannot be typed in by application code (no column default left)", async () => {
    const schema = databaseSchema();
    const pool = new Pool({ connectionString: testConnectionString() });
    try {
      const defaults = await pool.query(
        `select count(*)::int as n
           from pg_attrdef ad
           join pg_class c on c.oid = ad.adrelid
           join pg_namespace n on n.oid = c.relnamespace
           join pg_attribute a on a.attrelid = ad.adrelid and a.attnum = ad.adnum
          where n.nspname = $1 and c.relname in ('wallet_transactions', 'wallet_topup_requests')
            and a.attname = 'reference'`,
        [schema]
      );
      expect(defaults.rows[0].n).toBe(0);

      const triggers = await pool.query(
        `select c.relname, t.tgname
           from pg_trigger t
           join pg_class c on c.oid = t.tgrelid
           join pg_namespace n on n.oid = c.relnamespace
          where n.nspname = $1 and not t.tgisinternal
            and c.relname in ('wallet_transactions', 'wallet_topup_requests')
          order by c.relname`,
        [schema]
      );
      const names = triggers.rows.map((r) => `${r.relname}:${r.tgname}`);
      expect(names).toContain("wallet_transactions:wallet_transactions_reference");
      expect(names).toContain("wallet_topup_requests:wallet_topup_requests_reference");
    } finally {
      await pool.end();
    }
  });
});
